language: python
python:
    - "2.7"

sudo: required

jobs:
    include:
    - stage: "Build"
      name: "Ren'Py 6.99.12.4 SDK"
      install:
        - cd ..
        - wget https://www.renpy.org/dl/6.99.12.4/renpy-6.99.12.4-sdk.tar.bz2
        - tar xf renpy-6.99.12.4-sdk.tar.bz2
        - rm renpy-6.99.12.4-sdk.tar.bz2
        - mv renpy-6.99.12.4-sdk renpy

        - mkdir mod
        - mkdir "./mod/game"

        - rm -rf CatalinaToriel/game/README.html && cp -vRf CatalinaToriel/game/* mod/game/

        - bash CatalinaToriel/travis/inject_version.sh
        - bash CatalinaToriel/travis/inject_rp6.sh
        - cd renpy
      env:
        - SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy
      script: ./renpy.sh "../mod/" lint && ./renpy.sh launcher distribute "../mod/" && cd ..
    - stage: "Build"
      name: "Ren'Py Latest SDK"
      install:
        - cd ..
        - wget https://www.renpy.org/dl/7.3.2/renpy-7.3.2-sdk.tar.bz2
        - tar xf renpy-7.3.2-sdk.tar.bz2
        - rm renpy-7.3.2-sdk.tar.bz2
        - mv renpy-7.3.2-sdk renpy

        - mkdir mod
        - mkdir "./mod/game"

        - rm -rf CatalinaToriel/game/README.html && cp -vRf CatalinaToriel/game/* mod/game/

        - bash CatalinaToriel/travis/inject_version.sh
        - cd renpy
      env:
        - SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy
      script: ./renpy.sh "../mod/" lint && ./renpy.sh launcher distribute "../mod/" && cd ..

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file_glob: true
  file: "*-dists/*-_ASBaseSystem*.zip"
  skip_cleanup: true
  on:
    tags: true
