language: python
python:
    - "2.7"

sudo: required

jobs:
    include:
    - stage: "Build"
      name: "Ren'Py 6.99.12.4 SDK"
      install:
        - cd ..
        - bash aliceos/travis/install.sh 6.99.12.4

        - mkdir mod
        - mkdir "./mod/game"

        - rm -rf aliceos/game/README.html && cp -vRf aliceos/game/* mod/game/

        - bash aliceos/travis/inject_version.sh
        - bash aliceos/travis/inject_rp6.sh

        - cd renpy
      env:
        - SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy
      script: ./renpy.sh "../mod/" lint && ./renpy.sh launcher distribute "../mod/" && cd ..
    - stage: "Build"
      name: "Ren'Py Latest SDK"
      install:
        - cd ..
        - bash aliceos/travis/install.sh 7.3.2

        - mkdir mod
        - mkdir "./mod/game"

        - rm -rf aliceos/game/README.html && cp -vRf aliceos/game/* mod/game/

        - bash aliceos/travis/inject_version.sh
        - cd renpy
      env:
        - SDL_AUDIODRIVER=dummy SDL_VIDEODRIVER=dummy
      script: ./renpy.sh "../mod/" lint && ./renpy.sh launcher distribute "../mod/" && cd ..

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file_glob: true
  file: "*-dists/*-_ASBaseSystem*.zip"
  skip_cleanup: true
  on:
    tags: true
