name: Build AliceOS Archive
on:
  push:
    branches:
      - '*'
  release:
    types: [published]


jobs:
  build:
    name: Build with Ren'Py (Latest SDK)
    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: Install Ren'Py SDK
        shell: bash
        run: |
          cd ..
          aliceos/travis/install.sh 7.3.2
      - name: Setup AliceOS for build
        shell: bash
        run: |
          cd ..
          mkdir mod
          mkdir "./mod/game"
          rm -rf aliceos/game/README.html && cp -vRf aliceos/game/* mod/game/
          aliceos/travis/inject_version.sh
        env:
          TRAVIS_TAG: ${{ github.event.release.ref }}
          if: github.event_name == "release"
          TRAVIS_COMMIT: ${{ github.sha }}
      - name: Build AliceOS archive
        shell: bash
        run: |
          cd ../renpy
          ./renpy.sh launcher distribute "../mod/"
          cd ..
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
      - name: Release artifacts to GitHub Release
        uses: Roang-zero1/github-create-release-action@master
        if: github.event.name == "release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_TAG: ${{ github.event.release.ref }}
        with:
          args: 'AliceOS-${TRAVIS_TAG}-dists/AliceOS-${TRAVIS_TAG}-_ASBaseSystem.zip'



  build6:
    name: Build with Ren'Py (SDK v6.99.12.4)
    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: Install Ren'Py SDK
        shell: bash
        run: |
          cd ..
          aliceos/travis/install.sh 6.99.12.4
      - name: Setup AliceOS for build
        shell: bash
        run: |
          cd ..
          mkdir mod
          mkdir "./mod/game"
          rm -rf aliceos/game/README.html && cp -vRf aliceos/game/* mod/game/
          aliceos/travis/inject_version.sh
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
      - name: Build AliceOS archive
        shell: bash
        run: |
          cd ../renpy
          ./renpy.sh launcher distribute "../mod/"
          cd ..
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy