name: Build AliceOS Archive
on:
  push:
    branches:
      - '*'
  release:
    types: [published]


jobs:
  build:
    name: Ren'Py SDK Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        renpy-versions:
          - '7.3.2'
          - '6.99.12.4'
    steps:
      - name: Clone source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: Install Ren'Py SDK
        shell: bash
        run: |
          cd ..
          aliceos/travis/install.sh ${{ matrix.renpy-versions }}
      - name: Setup AliceOS for build
        shell: bash
        run: |
          cd ..
          mkdir mod
          mkdir "./mod/game"
          rm -rf aliceos/game/README.html && cp -vRf aliceos/game/* mod/game/
      - name: Add release tag to Build ID
        shell: bash
        run: |
          cd ..
          aliceos/travis/inject_version.sh
          cd ..
        if: github.event.release
        env:
          TRAVIS_TAG: ${{ github.ref }}
      - name: Add build hash to Build ID
        shell: bash
        run: |
          cd ..
          aliceos/travis/inject_version.sh
          cd ..
        if: contains(github.event_name, 'push')
        env:
          TRAVIS_COMMIT: ${{ github.sha }}
      - name: Build AliceOS archive
        shell: bash
        run: |
          cd ../renpy
          ./renpy.sh launcher distribute "../mod/"
          cd ..
          ls | grep 'AliceOS-' | cd
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
      - name: Release artifacts to GitHub Release
        uses: skx/github-action-publish-binaries@master
        if: github.event.release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ../AliceOS-*-dists/AliceOS-*-_ASBaseSystem.zip